### ISSUE TITLE
Compiled figma_plugin download

### ISSUE THREAD

**Issue by juancarlospaco** [treeform/fidget#101]
- Please provide a compiled `figma_plugin.js` to download, maybe GitHub Actions can automate it.

:)

**Comment by treeform** [comment]
I just need to try publishing the plugin again.

**Comment by tandy-1000** [comment]
any luck with republishing?

**Comment by treeform** [comment]
Plugin got approved and now you can just get it from here: https://www.figma.com/community/plugin/945866846468157120/Fidget-Export
