### ISSUE TITLE
[Question] why does image add prefix automatically?

### ISSUE THREAD

**Issue by xflywind** [treeform/fidget#107]
I'm doing some homeworks using fidget.

![image](https://user-images.githubusercontent.com/43030857/92680193-d8ea5c80-f35c-11ea-84c3-0cf837ab6710.png)

I use native file dialog in windows with `fidget` and it works fine. But I need to display image in window from the file dialog. `image` function will automatically add `data` prefix to path. I have to modify the source code to display images.

By the way sometimes I need to disable image cache. Now I have to set different names for the images. I hope `fidget` can supply this options. Are there some road maps for `fidget`, maybe I can  participate in:)

Thanks!

**Comment by treeform** [comment]
You should be able to set the `dataDir` to some thing else or "".

```nim
dataDir = ""
```

The reason for the data dir is that images might be part of APK, or stored on a different asset server.

https://github.com/treeform/fidget/blob/master/src/fidget/common.nim#L226
