### ISSUE TITLE
[FR] FOSS Figma replacement/alternative

### ISSUE THREAD

**Issue by ITwrx** [treeform/fidget#110]
I recently watched your nimconf video (very entertaining) and was excited to try Fidget out, but since i've never heard of Figma, i was suspicious as to it's possibly dubious origin. Sure enough: It's Enslaveware! This is a non-starter for me.  Please consider some human freedom-respecting alternative.
Thank you.

**Comment by treeform** [comment]
Sorry, I am a capitalists. I pay for good tools when they exist. I don't work for free for others and I don't expect others to work for free for me.

**Comment by ITwrx** [comment]
@treeform Free Software doesn't necessarily have to have anything to do with Gratis software and has nothing to do with my point.
