### ISSUE TITLE
Unhandled exception in example: hn.nim (Hacker News)

### ISSUE THREAD

**Issue by Bahm** [treeform/fidget#113]
hn.nim throws a KeyError exception when [comments are disabled](https://news.ycombinator.com/item?id=24208817).

It works if you replace:

    characters $call.json["descendants"].getInt() & " comments"

With:

    try:
      characters $call.json["descendants"].getInt() & " comments"
    except KeyError:
      characters "comments disabled"

The HN website just says "3 hours ago | hide" so it isn't a perfect match.

Here's the JSON for a HN post with comments disabled:

    {
      "by": "thomaspaulmann",
      "id": 25217586,
      "score": 1,
      "time": 1606374063,
      "title": "Raycast (YC W20) Is Hiring Fullstack Software Engineers (EU, Remote)",
      "type": "job",
      "url": "https://raycast.com/jobs/software-engineer-fullstack"
    }

**Comment by alt-tosc** [comment]
Similar issue, solved with a similar fix:
```nim
try:
  let uri = parseUri(call.json["url"].getStr())
  characters "(" & uri.hostname & ")"
except KeyError:
  characters ""
```

**Comment by treeform** [comment]
Thanks, ill fix it!

**Comment by treeform** [comment]
Fixed: https://github.com/treeform/fidget/commit/e67ff45251a190e9d032654e193630ec0f6f9d66
