### ISSUE TITLE
layoutAlign laInherit is built by plugin but missing in fidget code

### ISSUE THREAD

**Issue by ridcully99** [treeform/fidget#118]
I created a small layout and tried to export it with the plugin, but the code, the plugin creates produces error 'undefined identifier laInherit'.

```
frame "Frame 1":
        box -382, -311, 601, 565
        fill "#2d6349"
        layoutAlign laInherit
```

**Comment by treeform** [comment]
I think this is due to the new layout that was introduced couple of weeks ago. I don't have support for it yet.

**Comment by ridcully99** [comment]
Thanks for your feedback. I guess I can remove it from the code or replace with something that is already supported.
