### ISSUE TITLE
ellipse is built by plugin but missing in fidget code: undeclared identifier: 'ellipse'

### ISSUE THREAD

**Issue by ridcully99** [treeform/fidget#119]
I created a little layout and exported it with figma plugin, but the exported code produces error: undeclared identifier: 'ellipse'

```
ellipse "Ellipse 1":
      box 0, 0, 20, 25
      constraints cScale, cScale
      fill "#ff0000"
```

**Comment by treeform** [comment]
Yes most geometric commands like ellipse are missing at the moment.

**Comment by ridcully99** [comment]
Thanks for answering. I had a closer look at the code now and also at the demo and saw that I can use a rectangle with rounded corners instead for now. Also digged down into the code to see if I could help implementing missing geometrics but it becomes very low level and it's been quite I while that I learned about image algorithms. So I'll leave this to you. But let me say that I am very impressed with your code and the vast amount of projects you do with nim.

**Comment by treeform** [comment]
I am working on code that can do all of the primitives in pixie first.
