### ISSUE TITLE
fidget causes `nim-lang/Nim` packages CI to fail

### ISSUE THREAD

**Issue by ee7** [treeform/fidget#121]
See https://github.com/nim-lang/Nim/commit/73299b048f57838d83a3a8159909386a0905e553 and [the log](https://github.com/nim-lang/Nim/runs/1529569736#step:11:531):

```
    Compiling /home/runner/work/Nim/Nim/pkgstemp/fidget/tests/test (from package fidget) using c backend
  /home/runner/.nimble/pkgs/typography-0.6.0/typography/font.nim(25, 22) Error: undeclared identifier: 'Segment'
```

It looks like this is due to a recent change in https://github.com/treeform/bumpy/ or https://github.com/treeform/pixie/.

I'll ping @guzba here, since they aren't watching this repo and it looks like they might also know how to fix it.

**Comment by treeform** [comment]
I think I fixed this. CI is green now. Please confirm in the Nim repo.

**Comment by xflywind** [comment]
see https://github.com/nim-lang/Nim/pull/16319

**Comment by timotheecour** [comment]
before closing this, would be worth investigating why CI didn't catch this

**Comment by guzba** [comment]
@timotheecour CI doesn't run across repos. The issue was typography needed a new release to depend on updated repos.
