### ISSUE TITLE
README - Native examples for Windows, macOS, and Linux

### ISSUE THREAD

**Issue by Eloitor** [treeform/fidget#124]
I think that the section in the README about native examples is outdated:

 - I can't find any file named `fonts.nim` in this repository, but it is mentioned in the README.

**Comment by treeform** [comment]
Thank you for the bug report!

I have removed the mention of `fonts.nim` from the read me. It has moved to the test folder under `fontmetrics`.

https://github.com/treeform/fidget/commit/06c0a4cfa9616693862133a839586cf323b91028
