### ISSUE TITLE
fidget 2?

### ISSUE THREAD

**Issue by ridcully99** [treeform/fidget#125]
I read in a comment of an open pull request, that you're working on a fidget 2 already? Is there any more detailed information on that?

**Comment by treeform** [comment]
Yes I am working on fidget 2, I am taking a slightly different approach so it's a complete rewrite.

**Comment by WilliamBehrens** [comment]
@treeform Is fidget 2 going to be in the same package or will it be separate?

**Comment by treeform** [comment]
I am not sure. It's currently a separate repo. But it might be nice to keep a simpler name.

**Comment by juancarlospaco** [comment]
So... this still holds?, because I see new cool work being done on fidget1, but you said that you will not work on 1 anymore,
so fidget2 does not give the expected results ?, you are continuing fidget1 ?, 
if someone starts a GUI today should I use fidget1 or  ...wait ?.
:thinking:

**Comment by treeform** [comment]
We only updated some deps in fidget1, most work is being done in fidget 2.

**Comment by Nuc1eoN** [comment]
> I am not sure. It's currently a separate repo. But it might be nice to keep a simpler name.

Personally I say merge it into this repo once ready. Fidget has nearly 500 github stars and is just an awesome name in my opinion 💪

At least I will subscribe to the release channel of this repo and wait :D

**Comment by Clonkk** [comment]
> Personally I say merge it into this repo once ready. Fidget has nearly 500 github stars and is just an awesome name in my opinion 

+1. Merge the repo and use the versioning system. It's better for the visibility of the project. It's IMHO perfectly fine to justify a rewrite after a major version change. And people who wants to use fidget1 can still specify the version range they wish to use.

**Comment by treeform** [comment]
Sounds, good I will put the v2 code into this repo when its ready.
