### ISSUE TITLE
Install plugin on figma...

### ISSUE THREAD

**Issue by sparkrisp** [treeform/fidget#126]
Hi!, how could I install this plugin into figma? 

I can't compile it with npm run build because there is not packages.json

some help?

thanks!

**Comment by treeform** [comment]
I am working on a system which does not require a plugin, it will just use the API directly. 

You can just use the `tsc` to compile it, no need for npm run.

**Comment by treeform** [comment]
Plugin got approved and now you can just get it from here: https://www.figma.com/community/plugin/945866846468157120/Fidget-Export
