### ISSUE TITLE
.nimble/pkgs/flippy-0.4.7/flippy.nim(1, 22) Error: cannot open file: chroma/blends

### ISSUE THREAD

**Issue by HJarausch** [treeform/fidget#129]
Any example I try gives this error:
flippy.nim(1, 22) Error: cannot open file: chroma/blends

What am I missing?
Thanks for a hint,
Helmut

nim --version gives

Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-07
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 89a21e4ec71e705833d2aacd069e291cf41a19c6
active boot switches: -d:release

**Comment by treeform** [comment]
Thank you for the bug report!

This error has been fixed. Please update to the most recent version of fidget (and pixie).

**Comment by treeform** [comment]
Please update or reinstall fidget (so that it picks up the right versions of the libraries). 

Feel free to reopen if you are still having issues!

**Comment by mantielero** [comment]
I am having exactly the same issue. I have tried:
```
$ nimble refresh
$ nimble install https://github.com/treeform/fidget
$ nimble install pixie
```
which install: `fidget@0.7.7`.

**Comment by treeform** [comment]
Unfortunately this appears to be a problem in nimble not installing packages correctly.
