### ISSUE TITLE
Error compiling demos: .../.nimble/pkgs/pixie-0.0.15/pixie/images.nim(88, 28) Error: undeclared identifier: 'image'

### ISSUE THREAD

**Issue by joubertnel** [treeform/fidget#130]
As per title. 

For example, when I try to compile and run the minimal example with `nim c -r minimal.nim`, I get the following output:

> Hint: used config file '/usr/local/Nim/config/nim.cfg' [Conf]
> Hint: used config file '/usr/local/Nim/config/config.nims' [Conf]
> Hint: used config file '/usr/local/fidget/config.nims' [Conf]
> Hint: used config file '/usr/local/fidget/examples/config.nims' [Conf]
> ..............................................
> /Users/joubert/.nimble/pkgs/pixie-0.0.15/pixie/images.nim(88, 28) Error: undeclared identifier: 'image'

**Comment by treeform** [comment]
Would you mind updating pixie to 0.0.21 version and seeing if the error still happens?

I am on 0.0.21 and I don't see this error.

Also Mac or linux?

**Comment by treeform** [comment]
This issue has been fixed! Please update or reinstall fidget (so that it picks up the right versions of the libraries). 

Feel free to reopen if you are still having issues!
