### ISSUE TITLE
Minimal examples error out on compile 

### ISSUE THREAD

**Issue by nixfreak** [treeform/fidget#135]
nixfreak@chaosArch minimal]$ nim c -r minimal
Hint: used config file '/home/nixfreak/.choosenim/toolchains/nim-1.4.2/config/nim.cfg' [Conf]
Hint: used config file '/home/nixfreak/.choosenim/toolchains/nim-1.4.2/config/config.nims' [Conf]
Hint: used config file '/home/nixfreak/nim/fidget/config.nims' [Conf]
Hint: used config file '/home/nixfreak/nim/fidget/examples/config.nims' [Conf]
.................................................
/home/nixfreak/.nimble/pkgs/flippy-0.4.5/flippy.nim(292, 58) Error: undeclared identifier: 'Rect'

**Comment by treeform** [comment]
I think you have an old version of fidget. We have switched to using pixie. Can you update?

**Comment by treeform** [comment]
You need to have bumpy at right version.

Feel free to reopen if you still have an issue after updating.
