### ISSUE TITLE
Support for unicode char

### ISSUE THREAD

**Issue by SOVLOOKUP** [treeform/fidget#140]
After using demo in `examples/demo`, I find that it doesn't support displaying unicode chars like emoji or chinese/korea characters  even though I tried to change the font.

Will fidget support unicode text? It's important to me, thanks.

**Comment by treeform** [comment]
I do support chinese/korean characters but the font you use also needs to support it. Its rare for fonts too, most of the time it falls back to system. I don't have system fonts fall back. See the typography lib for more details: https://github.com/treeform/typography

![image](https://github.com/treeform/typography/raw/master/tests/rendered/ch.png)

I support hanazono font which support CJK:
https://github.com/treeform/typography/tree/master/tests/fonts/hanazono

I do not support emoji right now.
