### ISSUE TITLE
[Windows] Failed to open window.

### ISSUE THREAD

**Issue by Dev1lroot** [treeform/fidget#29]
```
nim c -r minimal.nim
minimal.exe
Failed to open window.
```

**Comment by skervista** [comment]
OpenGL 3?

**Comment by Dev1lroot** [comment]
4.0

**Comment by UNIcodeX** [comment]
I'm also getting a `Failed to open GLFW window.` after copying a working example for `hovers` to another windows machine and attempting to run over remote desktop. Placing the downloaded GLFW windows 64 bit libraries in the same directory as the demo executable, does not remedy the issue. I'm sure I'm missing something that may be otherwise obvious to you.

**Comment by treeform** [comment]
GLFW needs openGL to run. Maybe the problem with openGL drivers or some thing like that?

Please list your os and openGL names and versions.

**Comment by Dev1lroot** [comment]
Windows 10 1903 x64 , OpenGL 4.0 by NVIDIA DRIVER 342.01

**Comment by UNIcodeX** [comment]
Would this work for OpenGL apps over RDP perhaps? https://fdossena.com/?p=mesa/index.frag

**Comment by treeform** [comment]
I never tried openGL apps over RDP. I doubt it works over RDP as RDP is based on low level windows draw commands.

**Comment by UNIcodeX** [comment]
I got another Nim GUI demo to run over RDP with that Mesa library. I don't
remember which it was at the moment though. LOL

**Comment by UNIcodeX** [comment]
I think it was rdgui. Haven't really looked at the internals but the Mesa library in the same folder as the executable worked with it.

**Comment by retsyo** [comment]
I met the same problem in msys2+mingw64 on my windows 7 64 bits

however, the https://github.com/treeform/staticglfw/blob/master/examples/basic.nim can be compiled and run without any problem

**Comment by mchome** [comment]
Setting `openglVersion = (3, 3)` in `startFidget` fix my problem because default value is (4, 1).

**Comment by retsyo** [comment]
I used  `openglVersion = (4, 0)`, then I got
```
Hint: R:\fidget\examples\minimal\minimal.exe  [Exec]
3.4.0 Win32 WGL EGL OSMesa MinGW
GL_VERSION:4.0.0 - Build 9.17.10.2963
GL_SHADING_LANGUAGE_VERSION:4.00 - Build 9.17.10.2963
Vertex shader compilation failed:
R:\fidget\examples\minimal\minimal.nim(14) minimal
C:\Users\USER\.nimble\pkgs\fidget-0.3.2\fidget\openglbackend.nim(316) startFidget
C:\Users\USER\.nimble\pkgs\fidget-0.3.2\fidget\openglbackend.nim(297) runFidget
C:\Users\USER\.nimble\pkgs\fidget-0.3.2\fidget\openglbackend.nim(259) setupFidget
C:\Users\USER\.nimble\pkgs\fidget-0.3.2\fidget\opengl\context.nim(101) newContext
C:\Users\USER\.nimble\pkgs\fidget-0.3.2\fidget\opengl\shaders.nim(223) newShader
C:\Users\USER\.nimble\pkgs\fidget-0.3.2\fidget\opengl\shaders.nim(101) compileShaderFiles
E:\msys64\home\USER\_nim\nim\lib\core\macros.nim(557) getErrorLog
E:\msys64\home\USER\_nim\nim\lib\system.nim(2451) []
E:\msys64\home\USER\_nim\nim\lib\system\fatal.nim(49) sysFatal
Error: unhandled exception: value out of range: -2 notin 0 .. 9223372036854775807 [RangeDefect]
Error: execution of an external program failed: 'R:\fidget\examples\minimal\minimal.exe '

```

**Comment by retsyo** [comment]
further more, no matter I use `openglVersion = (4, 0)` in `startFidget` or not, the produced EXE file can run on my win 10 64 bits

**Comment by treeform** [comment]
@mchome, @retsyo I think the problem here is that I requires openGL 4. But your systems only support OpenGL 3. I need to make OpenGL 3 compatible shaders.

**Comment by treeform** [comment]
Hey I tagged a new release (0.4.2) that is known to fix some linux bugs. Please give it a try.

**Comment by treeform** [comment]
I believe this has been fixed.

Here is the packages you need for GUI development (and run tests) on Ubuntu:

```
sudo apt install -y  build-essential libalut-dev libasound2-dev libc6-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev mesa-utils pkg-config xorg-dev xvfb
```

**Comment by retsyo** [comment]
@treeform 
nothing changed on my win7 64 bits. latest nim and fidget

```
$ nim
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-16

```

and
```
$ nimble path fidget
C:\Users\USER\.nimble\pkgs\fidget-0.4.2
```

when I try to compile and run
```
nim c -r minimal.nim
...
CC: minimal.nim
Hint:  [Link]
Hint: 183413 lines; 27.437s; 226.516MiB peakmem; Debug build; proj: R:\fidget-master\examples\minimal\minimal.nim; out: R:\fidget-master\examples\minimal\minimal.exe [SuccessX]
Hint: R:\fidget-master\examples\minimal\minimal.exe  [Exec]
Failed to open window.
Error: execution of an external program failed: 'R:\fidget-master\examples\minimal\minimal.exe '
```
