### ISSUE TITLE
Error: execution of an external compiler program 

### ISSUE THREAD

**Issue by divy-work** [treeform/fidget#31]
Here's the whole error:
```
Error: execution of an external compiler program 'gcc -c  -w -D_GLFW_X11  -I/home/divy/.choosenim/toolchains/nim-1.0.6/lib -I/home/divy/fidget/examples/bars -o /home/divy/.cache/nim/bars_d/x11_init.c.o /home/divy/.nimble/pkgs/staticglfw-4.0.1/staticglfw/x11_init.c' failed with exit code: 1

In file included from /home/divy/.nimble/pkgs/staticglfw-4.0.1/staticglfw/internal.h:187:0,
                 from /home/divy/.nimble/pkgs/staticglfw-4.0.1/staticglfw/x11_init.c:30:
/home/divy/.nimble/pkgs/staticglfw-4.0.1/staticglfw/x11_platform.h:36:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
 #include <X11/Xcursor/Xcursor.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I'm trying to run the examples. And this error occurs for every one of them.
I am on Ubuntu 18.04 LTS.

Thanks.

**Comment by treeform** [comment]
I think you need the X11 development headers. Maybe this https://packages.ubuntu.com/search?keywords=libx11-dev

**Comment by divy-work** [comment]
Yup, I tried installing libx11-dev and turns out I already have the latest version.

`libx11-dev is already the newest version (2:1.6.4-3ubuntu0.2)`

**Comment by treeform** [comment]
I don't know what say. This feels like glfw issue on linux... I don't have a linux box with x11 to test this.

**Comment by divy-work** [comment]
Okay. I will try to reproduce this in Ubuntu 16.04 and ping the results here.

**Comment by luminosoda** [comment]
Fixed with `sudo apt install xorg-dev`

**Comment by treeform** [comment]
I now have linux in the github CI. You need all of this stuff: https://github.com/treeform/fidget/blob/master/.github/workflows/build.yml#L31

```sh
sudo apt update
sudo apt install -y  build-essential libalut-dev libasound2-dev libc6-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev mesa-utils pkg-config xorg-dev xvfb
```
