### ISSUE TITLE
Error: cannot open file: glfw3

### ISSUE THREAD

**Issue by mrhdias** [treeform/fidget#4]
Cannot run any of the examples because it says "Error: cannot open file: glfw3"

I tried to install the glfw3 library but it says it doesn't exist. But the glfw@3.3.0.2 library exists and is installed.

[install-info.txt](https://github.com/treeform/fidget/files/4008330/install-info.txt)
nim c -r bars.nim
...
Hint: dynlib [Processing]
Hint: input [Processing]
/home/hdias/Downloads/tmp/fidget/src/fidget/openglbackend/input.nim(1, 8) Warning: imported and not used: 'unicode' [UnusedImport]
Hint: perf [Processing]
Hint: strformat [Processing]
/home/hdias/Downloads/tmp/fidget/src/fidget/openglbackend/base.nim(4, 8) Error: cannot open file: glfw3

**Comment by treeform** [comment]
Sorry you need to install `nimrod-glfw >= 3.2.1`

**Comment by mrhdias** [comment]
Thanks. I uninstalled the package nim-glfw and installed the nimrod-glfw.

But none of the sample run.

I use Archlinux linux.

$ nim c -r todo.nim
Hint: used config file '/usr/local/programs/x86_64/nim-1.0.4/config/nim.cfg' [Conf]
Hint: operation successful (300 lines compiled; 0.050 sec total; 5.879MiB peakmem; Debug Build) [SuccessX]
Hint: /home/hdias/Downloads/tmp/fidget/examples/todo/todo  [Exec]
Failed to intialize GLFW.
Error: execution of an external program failed: '/home/hdias/Downloads/tmp/fidget/examples/todo/todo '

**Comment by treeform** [comment]
Looks like something is wrong with glfw itself. Not sure I can help here. I
have not done any testing in Arch before.

**Comment by mrhdias** [comment]
Strange issue with nimrod-glfw the GLFW fail, but if I install nim-glfw package the GLFW works fine.

$ git clone https://github.com/rafaelvasco/nimrod-glfw
$ cd nimrod-glfw/test
$ nim c -r -d:release --app:gui glfwtest.nim
glfwtest.nim(4)          glfwtest
Error: unhandled exception: Failed to Initialize GLFW [Exception]

$ nimble uninstall glfw
$ nimble install glfw
$ git clone https://github.com/ephja/nim-glfw
$ cd nim-glfw/examples
$ nim c -r -d:glfwStaticLib boing.nim

![Screenshot from 2019-12-29 21-21-03](https://user-images.githubusercontent.com/589045/71563089-f0f5a680-2a81-11ea-960c-e38c234810ee.png)

**Comment by mrhdias** [comment]
I opened a issue!
https://github.com/rafaelvasco/nimrod-glfw/issues/14

**Comment by mrhdias** [comment]
> I opened a issue!
> [rafaelvasco/nimrod-glfw#14](https://github.com/rafaelvasco/nimrod-glfw/issues/14)

I think the nimrod-glfw is not maintained anymore!

**Comment by treeform** [comment]
I experimented with my own wrapper here: https://github.com/treeform/staticglfw I will probably use this one as it does not require an extra DLL.

**Comment by treeform** [comment]
I have fixed the nimble file can you try reinstalling this package (which should fix the dependencies) and see if it works for you?

**Comment by mrhdias** [comment]
It works. Good work. Thanks
![Screenshot from 2020-01-17 21-22-01](https://user-images.githubusercontent.com/589045/72647068-8c868280-396f-11ea-81dc-27c641e086d1.png)

**Comment by treeform** [comment]
Nice and now with no dynamic linked libraries to ship! All static.
