### ISSUE TITLE
How to export from Figma?

### ISSUE THREAD

**Issue by MnlPhlp** [treeform/fidget#5]
How can i export projects from figma to this?
I cant find fidgetgen mentioned in the figma example.
Can i somehow import the figma extension to figma?

**Comment by treeform** [comment]
Yes, you can add the figma plugin from: https://github.com/treeform/fidget/tree/master/figma_plugin as a dev plugin. I plan to publish it as a real plugin when fidget gets more mature.

You will need to install typescript and compile it with `sudo npm install -g typescript` and `tsc` 

![image](https://user-images.githubusercontent.com/125948/72369833-c4fb3780-36b5-11ea-9de5-cfb42c3491ef.png)

Then its just text inside Figma:

![image](https://user-images.githubusercontent.com/125948/72370025-2c18ec00-36b6-11ea-95ef-75b83d4a4073.png)

**Comment by MnlPhlp** [comment]
Thanks for the explanation I'll try that tomorrow
