### ISSUE TITLE
example compilation error

### ISSUE THREAD

**Issue by btbytes** [treeform/fidget#73]
command executed:
```
nim c -r minimal
```

actual output:
```
/Users/pradeep/.nimble/pkgs/opengl-#head/opengl/private/errors.nim(27, 30) Error: type mismatch: got <int>
but expected one of:
proc `<`(x, y: int): bool
  first type mismatch at position: 2
  missing parameter: y
proc `<`(x, y: int64): bool
  first type mismatch at position: 2
  missing parameter: y
19 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: <len(params)
```

**Comment by treeform** [comment]
looks like that error is in side opengl. What version of nim compiler do you have? Have you tried the most recent 1.2 ?

**Comment by btbytes** [comment]
The version I used to compile is 1.2.0

```
$ nim -v
Nim Compiler Version 1.2.0 [MacOSX: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by treeform** [comment]
Maybe try uninstalling and reinstalling the openGL library?

https://github.com/nim-lang/opengl/issues

The compiler error you are getting is in the openGL lib not my code (`opengl/private/errors.nim(27, 30)`). I can't help you with it. Maybe open a ticket with openGL tracker?

**Comment by jorisbontje** [comment]
I have created a ticket for this in the `opengl` repo as I am running into the same compilation error with nim 1.2.2 on OSX.
https://github.com/nim-lang/opengl/issues/78
