### ISSUE TITLE
Join Immediate Mode UI organization

### ISSUE THREAD

**Issue by dumblob** [treeform/fidget#79]
Thanks for presenting Fidget on Nim conference! Was interesting to learn about the Figma->Fidget workflow etc.

I find it interesting, that you call this approach "imperative" without noting it's usually known under the term "immediate mode UI" construction :wink: (as opposed to "retained UI" construction).

I'm myself quite into immediate mode UIs and here I'd like to propose joining the [Immediate Mode UI organization](https://github.com/Immediate-Mode-UI/ ) whose purpose is to foster this UI construction style as well as being a hub of such UI libraries and last but not least a pool of motivated developer/maintainer "workforce".

There are no obligations (nor rules of any kind) in the org - it's really just to make projects more visible and networked.

**Comment by treeform** [comment]
I am not an expert on the terms. It feels like very one just makes up the terms as they go along. I am not exception.

The "immediate mode UI" means you draw the UI as you go. So if you draw some text, it gets drawn right a way, if you create a box it gets drawn right a way. This is not what happens in Fidget. 

* It creates a node tree first. 
* That node tree is diffed with previous node tree. 
* Then layout, animations, typesetting happens.
* The final node tree is drawn.

Its some place in-between "immediate mode UI" and "retained UI." I really like the immediate mode concepts, but they don't mesh with layout and animations well, that is why you need some "caching" and "diffing". Its more closer to "reactive UI" maybe?

**Comment by dumblob** [comment]
>I really like the immediate mode concepts, but they don't mesh with layout and animations well, that is why you need some "caching" and "diffing".

Maybe I wasn't clear enough - I actually meant exactly this (not the "plain immediate mode" where you actually draw immediately). Fell free to look at [Nuklear](https://github.com/Immediate-Mode-UI/Nuklear ) or [Quarks](https://github.com/Immediate-Mode-UI/Quarks ) - both have an intermediate representation (Quarks is a DOM, Nuklear has just an array of generic high-level instructions sometimes resembling a tree) which gets analyzed/clipped/manipulated/edited/whatever and first then drawn by a given backend.

I suppose nowadays no immediate mode library does it the "dumb way" and all of them offer some kind of DOM or alike :wink:.

But let's not worry about the naming - it's all the same principle and I think it makes sense to loosely group so similar initiatives together.

**Comment by treeform** [comment]
Sorry, I don't think I will be joining. I just don't get when I get out of it?

**Comment by dumblob** [comment]
@treeform more publicity among interested users as well as potential contributors who already contribute to other immediate mode libs in that organization. It also helps with general impression - being a part of bigger group/community puts more trust in the involved projects than if in a personal repository (akin to one-man-show).
