### ISSUE TITLE
Polygon element support

### ISSUE THREAD

**Issue by wiltzutm** [treeform/fidget#83]
Support for Figma's polygon element. Because there's lacking support of both polygons and unicodes in Fidget I cannot create arrow buttons. Maybe this is possible with images, but I like to use simple elements.

Thank you!

**Comment by treeform** [comment]
Polygon elements can be really complex. It will be a long time before I have support for polygons. I recommend marking your polygons with an export to PNG and exporting. Figma Fidget plugin automatically will insert image code there.

![image](https://user-images.githubusercontent.com/125948/85467760-7608d680-b560-11ea-80aa-2f456333a9ea.png)

```nim
component "icons/refresh":
  box 250, -415, 20, 20
  image "icons/refresh.png"
```

I support both 1x and 2x images for high DPI screens.

**Comment by wiltzutm** [comment]
Thanks a bunch for your quick answer and the alternative! When seeing your example it doesn't seem so difficult after all!
Sorry If I make my feature requests seem trivial, it's just because I don't understand what it takes to implement them. :)
