### ISSUE TITLE
Todo example is missing fonts

### ISSUE THREAD

**Issue by jorisbontje** [treeform/fidget#86]
```
/Users/username/Projects/nim/fidget/examples/todo/todo.nim(6) todo
/Users/username/Projects/nim/fidget/src/fidget/openglbackend.nim(392) loadFont
/Users/username/.nimble/pkgs/typography-#head/typography/opentype/parser.nim(730) readFontTtf
/Users/username/.nimble/pkgs/typography-#head/typography/opentype/parser.nim(719) readFontOtf
Error: unhandled exception: File does not exist. [IOError]
```

Looks like `IBMPlexSans-Regular.ttf` and `IBMPlexSans-Bold.ttf` are missing from fidget/examples/todo/data/

**Comment by treeform** [comment]
Sorry TODO example is still incomplete. My goal is to make it match the blog post comparing React with Vue. So that I can compare it to React and Vue as well.

**Comment by treeform** [comment]
I moved the todo example into old. I might resurrect it later but not right now.
