### ISSUE TITLE
demo example - Image and Constraint Menu Not responsive

### ISSUE THREAD

**Issue by sdmcallister** [treeform/fidget#89]
Very cool project. Thanks for doing it. 

Controls and Text  side menus function as expected.  'Controls' currently 'Contorls'. Image and Contstraint Menu do not change the main view.

Let me know if you need more specific information.

I'm on Fedora 32, Nim Compiler 1.2.4.

**Comment by treeform** [comment]
I have fixed the spelling issue. Thanks!

I did many improvements to the demo.
* Added Image Tab
* Added Constraints Tab
* Reworked the Text tab.
* Made all controls interactive.
