### ISSUE TITLE
Issues running examples on Osx 

### ISSUE THREAD

**Issue by nixfreak** [treeform/fidget#95]
Hello, 
     Just want to say thank you for developing this new gui lib. 

Issues:  The file compiles just fine using nim c --version  Nim Compiler Version 1.2.4 [MacOSX: amd64]
Compiled at 2020-07-22
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 54cb1eed34361bfd91b66541b2802bd0a68a4fae
active boot switches: -d:release

I then take this code 

`
import fidget                                                                               
                                                                                       
  loadFont("Inconsolata", "Inconsolata-Regular.ttf")                                          
                                                                                              
  setTitle("Pad of Code")                                                                     
                                                                                              
  var                                                                                         
    textValue = """                                                                           
  -- sql query                                                                                
  SELECT foo                                                                                  
  FROM bar                                                                                    
  WHERE a = 234 and b = "nothing"                                                             
  """                                                                                         
                                                                                              
  proc drawMain() =                                                                           
                                                                                              
    frame "main":                                                                             
      box 0, 0, parent.box.w-20, parent.box.h                                                 
      font "Inconsolata", 16.0, 400.0, 20, hLeft, vTop                                        
      fill "#F7F7F9"                                                                          
                                                                                              
      text "codebox":                                                                         
        box 0, 0, parent.box.w, parent.box.h                                                  
        fill "#000000"                                                                        
        multiline true                                                                        
        binding textValue                                                                     
                                                                                              
  startFidget(drawMain)
`

and compile via `nim c -r padofcode.nim` 
it compiles fine and gives me: 
Hint: 164910 LOC; 16.055 sec; 215.82MiB peakmem; Debug build; proj: /Users/.env/nim/fidget/padofcode/padofcode.nim; out: /.env/nim/fidget/padofcode/padofcode [SuccessX]

but gives me an error when trying to run it. 

""
Hint: /Users/.env/nim/fidget/padofcode/padofcode  [Exec]
/Users/.env/nim/fidget/padofcode/padofcode.nim(5) padofcode
/Users/.nimble/pkgs/fidget-0.4.2/fidget/openglbackend.nim(392) loadFont
/Users/.nimble/pkgs/typography-#head/typography/opentype/parser.nim(730) readFontTtf
/Users/.nimble/pkgs/typography-#head/typography/opentype/parser.nim(722) readFontOtf
/Users/.nimble/pkgs/typography-#head/typography/opentype/parser.nim(641) readFontOtf
/Users/.choosenim/toolchains/nim-1.2.4/lib/pure/collections/tables.nim(262) []
Error: unhandled exception: key not found: head [KeyError]
Error: execution of an external program failed: '/Users/.env/nim/fidget/padofcode/padofcode '
""

Here is my treeview:

.
├── data
│   └── Inconsolata-Regular.ttf
├── padofcode
└── padofcode.nim

**Comment by treeform** [comment]
Hmm `key not found: head` some thing is wrong with the font. HEAD chunk is the main chunk of the font. Could the font file be corrupted some how?
