### ISSUE TITLE
Cannot use system fonts in a simple manner

### ISSUE THREAD

**Issue by beef331** [treeform/fidget#97]
If passing a absolute directory to the `loadFont` procedure it fails due to the procedure not checking if it's relative. Currently requires 
```
let fontPath = relativePath("/usr/share/fonts/truetype/jetbrains-mono/JetBrainsMonoNL-Regular.ttf",dataDir)
loadFont("JetBrains", fontPath)
```

**Comment by treeform** [comment]
I added the ability to do that here: https://github.com/treeform/fidget/commit/2903ea930e84232fa6b38bf4c0315ddc61877f36

I still want most users to load fonts they ship.

But you can get around this by using `loadFontAbsolute()`
